config/routes.rb
Hadean::Application.routes.draw do

  resources :image_groups
  # mount Resque::Server.new, at: "/resque"

  namespace(:admin){ namespace(:customer_service){ resources :comments } }

  resources :user_sessions, only: [:new, :create, :destroy]

  get 'admin'       => 'admin/overviews#index'
  get 'login'       => 'user_sessions#new'
  get 'logout'      => 'user_sessions#destroy'
  delete 'logout'   => 'user_sessions#destroy'
  get 'signup'      => 'customer/registrations#new'
  get 'admin/merchandise' => 'admin/merchandise/summary#index'

  resource  :about,         only: [:show]
  resources :notifications, only: [:update]
  resources :products,      only: [:index, :show, :create]
  resources :states,        only: [:index]
  resources :terms,         only: [:index]
  resource  :unsubscribe,   only: :show
  resources :wish_items,    only: [:index, :destroy]

  root :to => "welcome#index"

  namespace :customer do
    resources :registrations,   only: [:index, :new, :create]
    resource  :password_reset,  only: [:new, :create, :edit, :update]
    resource  :activation,      only: [:show]
  end

  namespace :myaccount do
    resources :orders,        only: [:index, :show]
    resources :addresses
    resources :credit_cards
    resources :referrals,     only: [:index, :create, :update]
    resource  :store_credit,  only: [:show]
    resource  :overview,      only: [:show, :edit, :update]
  end

  namespace :shopping do
    resources  :addresses do
      member do
        put :select_address
      end
    end

    resources  :billing_addresses do
      member do
        put :select_address
      end
    end

    resources  :cart_items do
      member do
        put :move_to
      end
    end
    resource  :coupon, only: [:show, :create]

    resources  :orders do
      member do
        get :checkout
        get :confirmation
      end
    end
    resources  :shipping_methods
  end

  namespace :admin do
    namespace :customer_service do
      resources :users do
        resources :comments
      end
    end
    resources :users
    namespace :user_datas do

      resources :referrals do
        member do
          post :apply
        end
      end

      resources :users do
        resource :store_credits, only: [:show, :edit, :update]
        resources :addresses
      end
    end
    resources :overviews, only: [:index]

    get "help" => "help#index"

    namespace :reports do
      resource :overview, only: [:show]
      resources :graphs
      resources :weekly_charts, only: [:index]
    end
    namespace :rma do
      resources  :orders do
        resources  :return_authorizations do
          member do
            put :complete
          end
        end
      end
      #resources  :shipments
    end

    namespace :history do
      resources  :orders, only: [:index, :show] do
        resources  :addresses, only: [:index, :show, :edit, :update, :new, :create]
      end
    end

    namespace :fulfillment do
      resources  :orders do
        member do
          put :create_shipment
        end
        resources  :comments
      end

      namespace :partial do
        resources  :orders do
          resources :shipments, only: [ :create, :new, :update ]
        end
      end

      resources  :shipments do
        member do
          put :ship
        end
        resources  :addresses , only: [:edit, :update]# This is for editing the shipment address
      end
    end
    namespace :shopping do
      resources :carts
      resources :products
      resources :users
      namespace :checkout do
        resources :billing_addresses, only: [:index, :update, :new, :create, :select_address] do
          member do
            put :select_address
          end
        end
        resources :credit_cards
        resource  :order, only: [:show, :update, :start_checkout_process] do
          member do
            post :start_checkout_process
          end
        end
        resources :shipping_addresses, only: [:index, :update, :new, :create, :select_address] do
          member do
            put :select_address
          end
        end
        resources :shipping_methods, only: [:index, :update]
      end
    end
    namespace :config do
      resources :accounts
      resources :countries, only: [:index, :edit, :update, :destroy] do
        member do
          put :activate
        end
      end
      resources :overviews
      resources :shipping_categories
      resources :shipping_rates
      resources :shipping_methods
      resources :shipping_zones
      resources :tax_rates
      resources :tax_categories
    end

    namespace :generic do
      resources :coupons
      resources :deals
      resources :sales
    end
    namespace :inventory do
      resources :suppliers
      resources :overviews
      resources :purchase_orders
      resources :receivings
      resources :adjustments
    end

    namespace :merchandise do
      namespace :images do
        resources :products
      end
      resources :image_groups
      resources :properties
      resources :prototypes
      resources :brands
      resources :product_types
      resources :prototype_properties

      namespace :changes do
        resources :products do
          resource :property,          only: [:edit, :update]
        end
      end

      namespace :wizards do
        resources :brands,              only: [:index, :create, :update]
        resources :products,            only: [:new, :create]
        resources :properties,          only: [:index, :create, :update]
        resources :prototypes,          only: [:update]
        resources :tax_categories,      only: [:index, :create, :update]
        resources :shipping_categories, only: [:index, :create, :update]
        resources :product_types,       only: [:index, :create, :update]
      end

      namespace :multi do
        resources :products do
          resource :variant,      only: [:edit, :update]
        end
      end
      resources :products do
        member do
          get :add_properties
          put :activate
        end
        resources :variants
      end
      namespace :products do
        resources :descriptions, only: [:edit, :update]
      end
    end
    namespace :document do
      resources :invoices
    end
  end

end

app/controllers/admin/config/overviews_controller.rb
class Admin::Config::OverviewsController < Admin::Config::BaseController
  # GET /admin/config/overviews
  def index

  end

end

app/controllers/admin/inventory/overviews_controller.rb
class Admin::Inventory::OverviewsController < Admin::BaseController

  def index
    @products = Product.active.order("#{params[:sidx]} #{params[:sord]}").
                        includes({:variants => [{:variant_properties => :property}, :inventory]}).
                        paginate(:page => pagination_page, :per_page => pagination_rows)

  end

  def edit
    @product = Product.friendly.includes(:variants).find(params[:id])
  end

  def update
    @product = Product.friendly.find(params[:id])

    if @product.update_attributes(allowed_params)
      redirect_to action: :index
    else
      render action: :edit
    end
  end
  private

  def allowed_params
    params.require(:product).permit!
  end

end

app/controllers/admin/overviews_controller.rb
class Admin::OverviewsController < ApplicationController
  helper_method :recent_admin_users
  layout "admin"

  def index
    #  The index action should
    if u = User.first
      redirect_to root_url and return if !current_user
      redirect_to root_url unless current_user.admin?

    elsif Role.first
      ##  This means we don't have any users
      ##  First we need to create a user with all permissions

      @user = User.new(args)
      @user.password = password
      @user.password_confirmation = password
      if @user.active? || @user.activate!
        @user.save
        @user.role_ids = Role.all.map{|r| r.id }
        @user.save
        @current_user = @user
        @user_session = UserSession.new(session_args)
        @user_session.save
      end
    else
      ###  If you dont have roles you need to run rake db:seed
      @no_roles = true
    end
  end
  private
  def session_args
    @session_args ||= { :email => @user.email, :password => @password }
  end

  def args
    @password ||= "admin_user_#{rand(1000)}"
    @args ||= {
    :first_name => 'Admin',
    :last_name => 'User',
    :email => 'admin@notarealemail.com' }
  end

  def password
    @password ||= "admin_user_#{rand(1000)}"
  end

  def recent_admin_users
    []
  end

end

app/controllers/admin/reports/overviews_controller.rb
class Admin::Reports::OverviewsController < Admin::Reports::BaseController
  helper_method :start_time, :end_time
  before_action :set_time_range

  def show
    @accounting_report  = RorEReports::Accounting.new(start_time, end_time)
    @orders_report      = RorEReports::Orders.new(start_time, end_time)
    @customers_report   = RorEReports::Customers.new(start_time, end_time)
    @final_number_of_cart_items     = CartItem.before(end_time).last   ? CartItem.before(end_time).last.id   : 0
    @beginning_number_of_cart_items = CartItem.before(start_time).last ? CartItem.before(start_time).last.id : 0
  end

end

app/controllers/myaccount/overviews_controller.rb
class Myaccount::OverviewsController < Myaccount::BaseController
  def show

  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update_attributes(user_params)
      redirect_to myaccount_overview_url(), :notice  => "Successfully updated user."
    else
      render :edit
    end
  end

  private

    def user_params
      params.require(:user).permit(:password, :password_confirmation, :first_name, :last_name)
    end
    def selected_myaccount_tab(tab)
      tab == 'profile'
    end
end

app/views/admin/overviews/index.html.erb
<h2 style="text-align:center">Welcome to RoR Ecommerce!</h2>

<% if @password %>
  <p> Welcome, You are the Super Admin user. </p>
  <p>Your email and login is: <%= @user.email %> </p>
  <p>Your password is: <%= @password %> </p>
  <p>PLEASE WRITE THIS INFORMATION DOWN.</p>
<% end %>

<% if @no_roles %>
  <p>
    <b>You need to run rake db:seed</b>
  </p>
<% else %>
  <b>Best to go through the list below in separate tabs</b>
  <ol>
    <li>Go to <%= link_to 'Admin Users', admin_users_path, 'data-popup' => true %> and change your password and email to something you remember.</li>
    <li>Go to each of the config sections <%= link_to 'Accounts', admin_config_accounts_path, 'data-popup' => true %> ,
        <%= link_to 'Accounts', admin_config_accounts_path, 'data-popup' => true %>,
        <%= link_to 'Countries', admin_config_countries_path, 'data-popup' => true %>,
        <%= link_to 'Shipping Zones', admin_config_shipping_zones_path, 'data-popup' => true %>,
        <%= link_to 'Shipping Rates', admin_config_shipping_rates_path, 'data-popup' => true %>,
        <%= link_to 'Shipping Categories', admin_config_shipping_categories_path, 'data-popup' => true %>,
        <%= link_to 'Tax Rates', admin_config_tax_rates_path, 'data-popup' => true %>.</li>
    <li>Then create <%= link_to 'Properties', admin_merchandise_properties_path, 'data-popup' => true %>.  A property is just a characteristic that your products have.</li>
    <li>Add <%= link_to 'Product Type', admin_merchandise_product_types_path, 'data-popup' => true %></li>
    <li>Next create a <%= link_to 'Prototype', admin_merchandise_prototypes_path, 'data-popup' => true %>.  A prototype is the building block of a product.  The prototype is used to inherit the types of properties that your products will have.</li>
    <li>You should create a shipping category by going to <%= link_to 'Shipping Categories', admin_config_shipping_categories_path, 'data-popup' => true %>.</li>
    <li>Next create a <%= link_to 'Product', admin_merchandise_products_path, 'data-popup' => true %></li>
    <li>Next create a Variant.  A variant is a specific type of product.  If Diet Gatorade is your product, Fruit Punch Gatorage might be your variant. To
      do this click to edit your product and then click add variant.</li>
    <li>Next you need to upload Images.  To do this click to edit your product and then click add image.</li>
    <li>You need inventory .  To do this click <%= link_to 'Inventory', admin_inventory_overviews_path, 'data-popup' => true %>.  Then click purchase order and follow the step to create a purchase order.  Once the purchase order is complete, you need to click receive for the inventory to be in stock.
    </li>
  </ol>
<% end %>