config/routes.rb
Hadean::Application.routes.draw do

  resources :image_groups
  # mount Resque::Server.new, at: "/resque"

  namespace(:admin){ namespace(:customer_service){ resources :comments } }

  resources :user_sessions, only: [:new, :create, :destroy]

  get 'admin'       => 'admin/overviews#index'
  get 'login'       => 'user_sessions#new'
  get 'logout'      => 'user_sessions#destroy'
  delete 'logout'   => 'user_sessions#destroy'
  get 'signup'      => 'customer/registrations#new'
  get 'admin/merchandise' => 'admin/merchandise/summary#index'

  resource  :about,         only: [:show]
  resources :notifications, only: [:update]
  resources :products,      only: [:index, :show, :create]
  resources :states,        only: [:index]
  resources :terms,         only: [:index]
  resource  :unsubscribe,   only: :show
  resources :wish_items,    only: [:index, :destroy]

  root :to => "welcome#index"

  namespace :customer do
    resources :registrations,   only: [:index, :new, :create]
    resource  :password_reset,  only: [:new, :create, :edit, :update]
    resource  :activation,      only: [:show]
  end

  namespace :myaccount do
    resources :orders,        only: [:index, :show]
    resources :addresses
    resources :credit_cards
    resources :referrals,     only: [:index, :create, :update]
    resource  :store_credit,  only: [:show]
    resource  :overview,      only: [:show, :edit, :update]
  end

  namespace :shopping do
    resources  :addresses do
      member do
        put :select_address
      end
    end

    resources  :billing_addresses do
      member do
        put :select_address
      end
    end

    resources  :cart_items do
      member do
        put :move_to
      end
    end
    resource  :coupon, only: [:show, :create]

    resources  :orders do
      member do
        get :checkout
        get :confirmation
      end
    end
    resources  :shipping_methods
  end

  namespace :admin do
    namespace :customer_service do
      resources :users do
        resources :comments
      end
    end
    resources :users
    namespace :user_datas do

      resources :referrals do
        member do
          post :apply
        end
      end

      resources :users do
        resource :store_credits, only: [:show, :edit, :update]
        resources :addresses
      end
    end
    resources :overviews, only: [:index]

    get "help" => "help#index"

    namespace :reports do
      resource :overview, only: [:show]
      resources :graphs
      resources :weekly_charts, only: [:index]
    end
    namespace :rma do
      resources  :orders do
        resources  :return_authorizations do
          member do
            put :complete
          end
        end
      end
      #resources  :shipments
    end

    namespace :history do
      resources  :orders, only: [:index, :show] do
        resources  :addresses, only: [:index, :show, :edit, :update, :new, :create]
      end
    end

    namespace :fulfillment do
      resources  :orders do
        member do
          put :create_shipment
        end
        resources  :comments
      end

      namespace :partial do
        resources  :orders do
          resources :shipments, only: [ :create, :new, :update ]
        end
      end

      resources  :shipments do
        member do
          put :ship
        end
        resources  :addresses , only: [:edit, :update]# This is for editing the shipment address
      end
    end
    namespace :shopping do
      resources :carts
      resources :products
      resources :users
      namespace :checkout do
        resources :billing_addresses, only: [:index, :update, :new, :create, :select_address] do
          member do
            put :select_address
          end
        end
        resources :credit_cards
        resource  :order, only: [:show, :update, :start_checkout_process] do
          member do
            post :start_checkout_process
          end
        end
        resources :shipping_addresses, only: [:index, :update, :new, :create, :select_address] do
          member do
            put :select_address
          end
        end
        resources :shipping_methods, only: [:index, :update]
      end
    end
    namespace :config do
      resources :accounts
      resources :countries, only: [:index, :edit, :update, :destroy] do
        member do
          put :activate
        end
      end
      resources :overviews
      resources :shipping_categories
      resources :shipping_rates
      resources :shipping_methods
      resources :shipping_zones
      resources :tax_rates
      resources :tax_categories
    end

    namespace :generic do
      resources :coupons
      resources :deals
      resources :sales
    end
    namespace :inventory do
      resources :suppliers
      resources :overviews
      resources :purchase_orders
      resources :receivings
      resources :adjustments
    end

    namespace :merchandise do
      namespace :images do
        resources :products
      end
      resources :image_groups
      resources :properties
      resources :prototypes
      resources :brands
      resources :product_types
      resources :prototype_properties

      namespace :changes do
        resources :products do
          resource :property,          only: [:edit, :update]
        end
      end

      namespace :wizards do
        resources :brands,              only: [:index, :create, :update]
        resources :products,            only: [:new, :create]
        resources :properties,          only: [:index, :create, :update]
        resources :prototypes,          only: [:update]
        resources :tax_categories,      only: [:index, :create, :update]
        resources :shipping_categories, only: [:index, :create, :update]
        resources :product_types,       only: [:index, :create, :update]
      end

      namespace :multi do
        resources :products do
          resource :variant,      only: [:edit, :update]
        end
      end
      resources :products do
        member do
          get :add_properties
          put :activate
        end
        resources :variants
      end
      namespace :products do
        resources :descriptions, only: [:edit, :update]
      end
    end
    namespace :document do
      resources :invoices
    end
  end

end

app/models/deal.rb
# == Class Deal
#
#  The deal model is basically a "buy X get y percent free" or "buy X get y dollars off"
#
#  In the scenario "buy X get y percent free", X is buy_quantity and y is get_percentage.
#  The way it works get_percentage is multiplied by the lowest costing item that "qualifies" for the deal.
#
#  NOTE: "qualifies" =>  a product qualifies if is of the correct product_type_id.  If
#        the product_type_id doesn't match it will not qualify.  so you might have three pants
#        but also one belt.  the belt and the pants will not be the same product_type_id.

#  In the scenario "buy X get y dollars off", X is buy_quantity and y is get_amount.
#  The way it works get_amount is the number of cents reduced from the order total.
#  Again the NOTE above about "qualifies" still is in effect

# == Schema Information
#
# Table name: deals
#
#  id              :integer          not null, primary key
#  buy_quantity    :integer          not null
#  get_percentage  :integer
#  deal_type_id    :integer          not null
#  product_type_id :integer          not null
#  get_amount      :integer
#  deleted_at      :datetime
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class Deal < ApplicationRecord

  validates :buy_quantity,            presence: true
  validates :get_percentage,          presence: true, :if => :get_amount_is_blank?
  validates :product_type_id,         presence: true
  validates :get_amount,              presence: true, :if => :get_percentage_is_blank?
  #validates :description,             presence: true, length: {:maximum => 255}

  belongs_to :deal_type
  belongs_to :product_type

  def self.best_qualifing_deal(order)
    product_type_and_amount_hash = order.number_of_a_given_product_type.sort_by{|v| v.last.size }.reverse # sort the hashes by the number of items for that product type
    deal_time = order.completed_at || order.deal_time || Time.zone.now # Deal.best_qualifing_deal(ooo)
    Hash[product_type_and_amount_hash].each_pair do |product_type_id, product_type_prices|
      deal_amount = qualifing_deal(product_type_id, product_type_prices, deal_time)
      return deal_amount.round_at(2) if deal_amount
    end
    0.0
  end
  def self.qualifing_deal(product_type_id, product_type_prices, at)
    deal = self.for_x_number_purchased(product_type_prices.size).
    for_product_type_id(product_type_id).existed_at(at).active_at(at).
    order('deals.get_percentage DESC').first
    deal ? deal.final_deal_amount(product_type_prices) : false
  end

  def self.for_x_number_purchased(num)
    where(['deals.buy_quantity <= ?', num])
  end

  def self.active_at(at)
    where(['deals.deleted_at >= ? OR deals.deleted_at IS NULL', at])
  end

  def self.existed_at(at)
    where(['deals.created_at <= ?', at])
  end

  def self.for_product_type_id(product_type_id)
    where(['deals.product_type_id IN (?)', product_type_id])
  end

  def final_deal_amount(product_type_prices)
    if get_amount && get_amount > 0.0
      get_amount.to_f / 100.0
    else
      ((product_type_prices.sort.reverse[0..(buy_quantity - 1)].min) * get_percentage).to_f / 100.0
    end
  end

  private
    def get_percentage_is_blank?
      get_percentage.blank?
    end
    def get_amount_is_blank?
      get_amount.blank?
    end
end

app/models/deal_type.rb
class DealType < ApplicationRecord

  validates :name,            presence: true

  has_many :deals
  TYPES = ['Buy X Get % off', 'Buy X Get $ off']
end

app/controllers/admin/generic/base_controller.rb
class Admin::Generic::BaseController < Admin::BaseController

end

app/controllers/admin/generic/coupons_controller.rb
class Admin::Generic::CouponsController < Admin::Generic::BaseController
  def index
    @coupons = Coupon.all
  end

  def show
    @coupon = Coupon.find(params[:id])
  end

  def new
    form_info
    @coupon = Coupon.new
  end

  def create
    @coupon = Coupon.new(allowed_params)
    @coupon.type = params[:c_type]
    @coupon.errors.add(:base, 'please select coupon type') if params[:c_type].blank?
    if @coupon.errors.size == 0 && @coupon.save
      flash[:notice] = "Successfully created coupon."
      redirect_to admin_generic_coupon_url(@coupon)
    else
      form_info
      render :action => 'new'
    end
  end

  def edit
    form_info
    @coupon = Coupon.find(params[:id])
  end

  def update
      @coupon = Coupon.find(params[:id])
    if @coupon.update_attributes(allowed_params)
      flash[:notice] = "Successfully updated coupon."
      redirect_to admin_generic_coupon_url(@coupon)
    else
      form_info
      render :action => 'edit'
    end
  end

  def destroy
    @coupon = Coupon.find(params[:id])
    @coupon.destroy
    flash[:notice] = "Successfully destroyed coupon."
    redirect_to admin_generic_coupons_url
  end

  private

  def allowed_params
    params.require(:coupon).permit(:code, :amount, :minimum_value, :percent, :description, :combine, :starts_at, :expires_at)
  end

  def form_info
    @coupon_types = Coupon::COUPON_TYPES
  end
end

app/controllers/admin/generic/deals_controller.rb
class Admin::Generic::DealsController < Admin::Generic::BaseController
  helper_method :sort_column, :sort_direction, :product_types,:deal_types
  def index
    @deals = Deal.order(sort_column + " " + sort_direction).
                                              paginate(:page => pagination_page, :per_page => pagination_rows)
  end

  def show
    @deal = Deal.find(params[:id])
  end

  def new
    @deal = Deal.new
  end

  def create
    @deal = Deal.new(allowed_params)
    if @deal.save
      redirect_to [:admin, :generic, @deal], :notice => "Successfully created deal."
    else
      render :new
    end
  end

  def edit
    @deal = Deal.find(params[:id])
  end

  def update
    @deal = Deal.find(params[:id])
    if @deal.update_attributes(allowed_params)
      redirect_to [:admin, :generic, @deal], :notice  => "Successfully updated deal."
    else
      render :edit
    end
  end

  def destroy
    @deal = Deal.find(params[:id])
    @deal.deleted_at = Time.zone.now
    @deal.save
    redirect_to admin_generic_deals_url, :notice => "Successfully deleted deal."
  end

  private

    def allowed_params
      params.require(:deal).permit(:buy_quantity, :get_percentage, :deal_type_id, :product_type_id, :get_amount, :deleted_at)
    end

    def product_types
      @select_product_types     ||= ProductType.all.collect{|pt| [pt.name, pt.id]}
    end

    def deal_types
      @select_deal_types     ||= DealType.all.collect{|pt| [pt.name, pt.id]}
    end

    def sort_column
      Deal.column_names.include?(params[:sort]) ? params[:sort] : "buy_quantity"
    end

    def sort_direction
      %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
    end
end

app/controllers/admin/generic/sales_controller.rb
# Use this model to create 20% off sales for any given product

class Admin::Generic::SalesController < Admin::Generic::BaseController
  helper_method :sort_column, :sort_direction, :products
  def index
    @sales = Sale.order(sort_column + " " + sort_direction).
                                              paginate(:page => pagination_page, :per_page => pagination_rows)
  end

  def show
    @sale = Sale.find(params[:id])
  end

  def new
    @sale = Sale.new
  end

  def create
    @sale = Sale.new(allowed_params)
    if @sale.save
      redirect_to [:admin, :generic, @sale], :notice => "Successfully created sale."
    else
      render :new
    end
  end

  def edit
    @sale = Sale.find(params[:id])
  end

  def update
    @sale = Sale.find(params[:id])
    if @sale.update_attributes(allowed_params)
      redirect_to [:admin, :generic, @sale], :notice  => "Successfully updated sale."
    else
      render :edit
    end
  end

  def destroy
    @sale = Sale.find(params[:id])
    @sale.destroy
    redirect_to admin_generic_sales_url, :notice => "Successfully destroyed sale."
  end

  private

    def allowed_params
      params.require(:sale).permit(:product_id, :percent_off, :starts_at, :ends_at)
    end

    def products
      @products ||= Product.select([:id, :name]).map{|p| [p.name, p.id]}
    end

    def sort_column
      Sale.column_names.include?(params[:sort]) ? params[:sort] : "product_id"
    end

    def sort_direction
      %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
    end
end

app/views/admin/generic/deals/_form.html.erb
<%= f.error_messages %>
<div class='row'>
  <ul class='column large-5'>
    <li class="field">
      <%= f.label :buy_quantity %>
      <%= f.number_field :buy_quantity %>
    </li>
    <li class="field">
      <%= f.label :get_percentage %>
      <%= f.number_field :get_percentage %>
    </li>
    <li class="field">
      <%= f.label :deal_type_id do %>
        Deal Type
        <%= f.select :deal_type_id, deal_types, include_blank: true %>
      <% end %>
    </li>
  </ul>
  <ul class='column large-5 float-left'>
    <li class="field">
      <%= f.label :product_type_id %>
      <%= f.select :product_type_id, product_types, include_blank: true %>
    </li>
    <li class="field">
      <%= f.label :get_amount %>
      <%= f.number_field :get_amount %>
    </li>

  </ul>
</div>

app/views/admin/generic/deals/edit.html.erb
<h3>Edit Deal</h3>

<%= form_for @deal, :url => [:admin, :generic, @deal] do |f| %>
  <%=  render :partial => 'form', :locals => {:f => f} %>
  <div class="actions"><%= f.submit 'Update' , :class => 'button' %></div>
<% end %>

<p>
  <%= link_to "Show", [:admin, :generic, @deal], :class => 'button secondary' %>
  <%= link_to "View All", admin_generic_deals_path, :class => 'button secondary' %>
</p>

app/views/admin/generic/deals/index.html.erb
<div class="admin_title_header clearfix">
  <h3>Deals</h3>
  <%= link_to "New Deal", new_admin_generic_deal_path, :class => "button" %>
</div>

<div class="admin_deals">
  <table class='hover'>
    <thead>
    <tr class='odd'>
      <th  class='column1_header'><%= sortable 'buy_quantity', 'Buy Quantity' %></th>
      <th>Get Percentage</th>
      <th>Deal Type</th>
      <th>Product Type</th>
      <th>Get Amount</th>
      <th>Deleted At</th>
      <th></th>
      <th></th>
    </tr>
    </thead>
    <tbody>
    <% for deal in @deals %>
      <tr  class='<%= cycle("odd", "")%>'>

          <td><%= link_to deal.buy_quantity, [:admin, :generic, deal] %></td>
          <td><%= deal.get_percentage %></td>
          <td><%= deal.deal_type.name %></td>
          <td><%= deal.product_type.name %></td>
          <td><%= deal.get_amount %></td>
          <td><%= deal.deleted_at %></td>
        <td>
        <%#  YOU SHOULD NOT EDIT THIS..  OLD ORDERS WILL NO LONGER CALCULATE CORRECTLY.  set Deleted_at and create a new promotion %>
        <%#= link_to "edit", edit_admin_generic_deal_path(deal) %></td>
        <td><%= link_to "delete", [:admin, :generic, deal], :data => {:confirm => 'Are you sure?'}, :method => :delete %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

<%= will_paginate @deals %>

app/views/admin/generic/deals/new.html.erb
<h3>New Deal</h3>

<%= form_for @deal, url: admin_generic_deals_path(@deal) do |f| %>
  <%=  render partial: 'form', locals: { f: f } %>
  <div class="actions float-right">
    <%= f.submit 'Create', class: "button" %>
    <%= link_to "Back to List", admin_generic_deals_path, class: "button secondary" %>
  </div>
<% end %>

app/views/admin/generic/deals/show.html.erb
<h3>Deal</h3>

<ul>
  <li>
    <label>Buy Quantity:</label>
    <%= @deal.buy_quantity %>
  </li>
  <li>
    <label>Get Percentage:</label>
    <%= @deal.get_percentage %>
  </li>
  <li>
    <label>Deal Type:</label>
    <%= @deal.deal_type.name %>
  </li>
  <li>
    <label>Product Type:</label>
    <%= @deal.product_type.name %>
  </li>
  <li>
    <label>Get Amount:</label>
    <%= @deal.get_amount %>
  </li>
  <li>
    <label>Deleted At:</label>
    <%= @deal.deleted_at %>
  </li>
</ul>
<p>
  <%#  YOU SHOULD NOT EDIT THIS..  OLD ORDERS WILL NO LONGER CALCULATE CORRECTLY.  set Deleted_at and create a new promotion %>
  <%#= link_to "Edit", edit_admin_generic_deal_path(@deal), :class => 'button' %> |
  <%= link_to "Destroy", [:admin, :generic, @deal], :data => {:confirm => 'Are you sure?'}, :method => :delete, :class => 'button' %> |
  <%= link_to "View All", admin_generic_deals_path, :class => 'button' %>
</p>