config/routes.rb
Hadean::Application.routes.draw do

  resources :image_groups
  # mount Resque::Server.new, at: "/resque"

  namespace(:admin){ namespace(:customer_service){ resources :comments } }

  resources :user_sessions, only: [:new, :create, :destroy]

  get 'admin'       => 'admin/overviews#index'
  get 'login'       => 'user_sessions#new'
  get 'logout'      => 'user_sessions#destroy'
  delete 'logout'   => 'user_sessions#destroy'
  get 'signup'      => 'customer/registrations#new'
  get 'admin/merchandise' => 'admin/merchandise/summary#index'

  resource  :about,         only: [:show]
  resources :notifications, only: [:update]
  resources :products,      only: [:index, :show, :create]
  resources :states,        only: [:index]
  resources :terms,         only: [:index]
  resource  :unsubscribe,   only: :show
  resources :wish_items,    only: [:index, :destroy]

  root :to => "welcome#index"

  namespace :customer do
    resources :registrations,   only: [:index, :new, :create]
    resource  :password_reset,  only: [:new, :create, :edit, :update]
    resource  :activation,      only: [:show]
  end

  namespace :myaccount do
    resources :orders,        only: [:index, :show]
    resources :addresses
    resources :credit_cards
    resources :referrals,     only: [:index, :create, :update]
    resource  :store_credit,  only: [:show]
    resource  :overview,      only: [:show, :edit, :update]
  end

  namespace :shopping do
    resources  :addresses do
      member do
        put :select_address
      end
    end

    resources  :billing_addresses do
      member do
        put :select_address
      end
    end

    resources  :cart_items do
      member do
        put :move_to
      end
    end
    resource  :coupon, only: [:show, :create]

    resources  :orders do
      member do
        get :checkout
        get :confirmation
      end
    end
    resources  :shipping_methods
  end

  namespace :admin do
    namespace :customer_service do
      resources :users do
        resources :comments
      end
    end
    resources :users
    namespace :user_datas do

      resources :referrals do
        member do
          post :apply
        end
      end

      resources :users do
        resource :store_credits, only: [:show, :edit, :update]
        resources :addresses
      end
    end
    resources :overviews, only: [:index]

    get "help" => "help#index"

    namespace :reports do
      resource :overview, only: [:show]
      resources :graphs
      resources :weekly_charts, only: [:index]
    end
    namespace :rma do
      resources  :orders do
        resources  :return_authorizations do
          member do
            put :complete
          end
        end
      end
      #resources  :shipments
    end

    namespace :history do
      resources  :orders, only: [:index, :show] do
        resources  :addresses, only: [:index, :show, :edit, :update, :new, :create]
      end
    end

    namespace :fulfillment do
      resources  :orders do
        member do
          put :create_shipment
        end
        resources  :comments
      end

      namespace :partial do
        resources  :orders do
          resources :shipments, only: [ :create, :new, :update ]
        end
      end

      resources  :shipments do
        member do
          put :ship
        end
        resources  :addresses , only: [:edit, :update]# This is for editing the shipment address
      end
    end
    namespace :shopping do
      resources :carts
      resources :products
      resources :users
      namespace :checkout do
        resources :billing_addresses, only: [:index, :update, :new, :create, :select_address] do
          member do
            put :select_address
          end
        end
        resources :credit_cards
        resource  :order, only: [:show, :update, :start_checkout_process] do
          member do
            post :start_checkout_process
          end
        end
        resources :shipping_addresses, only: [:index, :update, :new, :create, :select_address] do
          member do
            put :select_address
          end
        end
        resources :shipping_methods, only: [:index, :update]
      end
    end
    namespace :config do
      resources :accounts
      resources :countries, only: [:index, :edit, :update, :destroy] do
        member do
          put :activate
        end
      end
      resources :overviews
      resources :shipping_categories
      resources :shipping_rates
      resources :shipping_methods
      resources :shipping_zones
      resources :tax_rates
      resources :tax_categories
    end

    namespace :generic do
      resources :coupons
      resources :deals
      resources :sales
    end
    namespace :inventory do
      resources :suppliers
      resources :overviews
      resources :purchase_orders
      resources :receivings
      resources :adjustments
    end

    namespace :merchandise do
      namespace :images do
        resources :products
      end
      resources :image_groups
      resources :properties
      resources :prototypes
      resources :brands
      resources :product_types
      resources :prototype_properties

      namespace :changes do
        resources :products do
          resource :property,          only: [:edit, :update]
        end
      end

      namespace :wizards do
        resources :brands,              only: [:index, :create, :update]
        resources :products,            only: [:new, :create]
        resources :properties,          only: [:index, :create, :update]
        resources :prototypes,          only: [:update]
        resources :tax_categories,      only: [:index, :create, :update]
        resources :shipping_categories, only: [:index, :create, :update]
        resources :product_types,       only: [:index, :create, :update]
      end

      namespace :multi do
        resources :products do
          resource :variant,      only: [:edit, :update]
        end
      end
      resources :products do
        member do
          get :add_properties
          put :activate
        end
        resources :variants
      end
      namespace :products do
        resources :descriptions, only: [:edit, :update]
      end
    end
    namespace :document do
      resources :invoices
    end
  end

end

app/controllers/admin/fulfillment/orders_controller.rb
class Admin::Fulfillment::OrdersController < Admin::Fulfillment::BaseController
  helper_method :sort_column, :sort_direction
  # GET /admin/fulfillment/orders
  def index
    @orders = Order.fulfillment_grid(params).order(sort_column + " " + sort_direction).
                                            paginate(:page => pagination_page, :per_page => pagination_rows)

  end

  # GET /admin/fulfillment/orders/1
  def show
    @order = Order.includes([:user, :shipments, {:order_items => [:shipment, :variant]}]).find(params[:id])
    add_to_recent_user(@order.user)
    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @order }
    end
  end

  # GET /admin/fulfillment/orders/1/edit
  def edit
    @order = Order.includes([:user, :shipments, {:order_items => [:shipment, :variant]}]).find(params[:id])
    add_to_recent_user(@order.user)
  end


  def create_shipment
    @order = Order.find_by_id(params[:id])
    if @order
      Shipment.create_shipments_with_items(@order)
      @order.reload
    end
  end

  # PUT /admin/fulfillment/orders/1
  def update
    @order    = Order.find_by_id(params[:id])
    @invoice  = @order.invoices.find(params[:invoice_id])

    @payment = @order.capture_invoice(@invoice)

##  several things happen on this request
# => Payment is captured
# => Invoice is updated to log leger transactions
# => Shipment is marked as ready to send and associated to the order_items
# => If everything works send the user to the shipment page


## TODO
# => Allow partial payments
# => mark only order_items that will be shipped

    if @payment && @payment.success?
      render partial: 'success_message'
    else
      render partial: 'failure_message'
    end
  end

  # DELETE /admin/fulfillment/shipments/1
  # DELETE /admin/fulfillment/shipments/1.xml
  def destroy

    @order    = Order.find(params[:id])
    @invoice  = @order.invoices.find(params[:invoice_id])

    @order.cancel_unshipped_order(@invoice)
    respond_to do |format|
      format.html { render :partial => 'invoice_details', :locals => {:invoice => @invoice} }
      format.json { render :json => @order.to_json }
    end
  end

  protected

  def sort_column
    Order.column_names.include?(params[:sort]) ? params[:sort] : "number"
  end

  def pagination_rows
    params[:rows] ||= 25
    params[:rows].to_i
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end
end

app/controllers/admin/history/orders_controller.rb
class Admin::History::OrdersController < Admin::BaseController
  # GET /admin/history/orders
  def index
    @orders = Order.find_finished_order_grid(params).paginate(:page => pagination_page, :per_page => pagination_rows)
  end

  # GET /admin/history/orders/1
  def show
    @order = Order.includes([:ship_address, :invoices,
                             {:shipments => :shipping_method},
                             {:order_items => [
                                                {:variant => [:product, :variant_properties]}]
                              }]).find_by_number(params[:id])
  end

end

app/controllers/admin/shopping/base_controller.rb
#The philosophy of the admin cart is 2-fold.
#
# First these people have admin privileges.  So lets not add security features that they are allowed to use anyway.
#
# Second, the number of people in the Admin Section will not be in the millions.
# => So lets use the mem_cache session store to store more information than we would normal.
# => This will hit the DB much less and should have better performance.

class Admin::Shopping::BaseController < Admin::BaseController
  helper_method :session_admin_cart, :reset_admin_cart#, :new_admin_cart#

  layout 'admin_cart'

  private

  def reset_admin_cart
    session[:admin_cart_id] = new_admin_cart.id
  end

  def session_admin_cart
    if session[:admin_cart_id]
      @admin_cart ||= Cart.find_by_id(session[:admin_cart_id])
      @admin_cart ||= new_admin_cart # just in case the session has a bad ID (normally in development while having 2 apps)
    else
      new_admin_cart
    end
  end

  def new_admin_cart
    @admin_cart = Cart.create(:user => current_user)
    session[:admin_cart_id] = @admin_cart.id
    @admin_cart
  end

  def next_admin_cart_form()
     # if cart is empty
    if !session_admin_cart.customer_id
      return admin_shopping_users_url
    elsif !session_admin_cart.shopping_cart_items
      return admin_shopping_products_url()
    #elsif session_admin_cart[:shipping_address].nil?
    #  return admin_shopping_shipping_addresses_url
    #elsif session_admin_cart[:billing_address].nil?
    #  return admin_shopping_billing_addresses_url()
    #elsif session_admin_cart[:shipping_rate].nil?
    #  return admin_shopping_shipping_methods_url()
    else
      return admin_shopping_products_url()
    #  return nil#admin_shopping_carts_url()
#    elsif session_admin_cart[:coupon].nil?
#      return admin_shopping_coupons_url()
    end
  end

end

app/controllers/admin/shopping/carts_controller.rb
class Admin::Shopping::CartsController < Admin::Shopping::BaseController

  # GET /admin/order/carts
  def index
    authorize! :create_orders, current_user
    if f = next_admin_cart_form
      redirect_to f
    else
      @cart = session_admin_cart
      @credit_card ||= ActiveMerchant::Billing::CreditCard.new()
    end
  end

  # DELETE /admin/order/carts/1
  def destroy
    session_admin_cart = nil
    redirect_to(admin_shopping_carts_url)
  end


  private

end

app/controllers/admin/shopping/checkout/base_controller.rb
class Admin::Shopping::Checkout::BaseController < Admin::Shopping::BaseController
  helper_method :session_admin_order

  private

  def checkout_user
    session_admin_cart.customer
  end

  def next_admin_order_form_url
    next_admin_order_form || admin_shopping_checkout_order_url
  end

  def next_admin_order_form()
     # if cart is empty
    if !session_admin_cart.customer_id
      return admin_shopping_users_url
    elsif !session_admin_cart.shopping_cart_items
      return admin_shopping_products_url()
    elsif session_admin_order.ship_address_id.nil?
      return admin_shopping_checkout_shipping_addresses_url
    elsif session_admin_order.bill_address_id.nil?
      return admin_shopping_checkout_billing_addresses_url()
    elsif session_admin_order.order_items.any?{|oi| oi.shipping_rate_id.nil?}
      return admin_shopping_checkout_shipping_methods_url()
    else
      return nil #admin_shopping_carts_url()
#    elsif session_admin_cart[:coupon].nil?
#      return admin_shopping_coupons_url()
    end
  end

  def session_admin_order
    find_or_create_order
  end

  def session_order_id
    session[:order_admin_id] ? session[:order_admin_id] : find_or_create_order.id
  end

  def find_or_create_order
    return @session_admin_order if @session_admin_order
    if session[:order_admin_id]
      @session_admin_order = checkout_user.orders.include_checkout_objects.find_by_id(session[:order_admin_id])
      create_order if !@session_admin_order || !@session_admin_order.in_progress?
    else
      create_order
    end
    @session_admin_order
  end


  def create_order
    @session_admin_order = checkout_user.orders.create(:number       => Time.now.to_i,
                                                :ip_address   => request.env['REMOTE_ADDR'],
                                                :bill_address => checkout_user.billing_address  )
    add_new_cart_items(session_cart.shopping_cart_items)
    session[:order_admin_id] = @session_admin_order.id
  end

  def add_new_cart_items(items)
    items.each do |item|
      @session_admin_order.add_items(item.variant, item.quantity)
    end
  end

  def order_completed!(order)
    session_admin_cart.mark_items_purchased(order)
    session[:admin_cart_id] = nil
    session[:order_admin_id] = nil
  end
  def countries
    @countries ||= Country.active
  end
end

app/controllers/admin/shopping/checkout/billing_addresses_controller.rb
class Admin::Shopping::Checkout::BillingAddressesController < Admin::Shopping::Checkout::BaseController
  helper_method :countries

  def index
    @billing_address = Address.new
    if !Settings.require_state_in_address  && countries.size == 1
      @billing_address.country = countries.first
    end
    form_info
  end

  def new
    old_address       = Address.find_by_id(params[:old_address_id])
    attributes        = old_address.try(:address_attributes)
    @billing_address = session_admin_cart.customer.addresses.new(attributes)
    if !Settings.require_state_in_address && countries.size == 1
      @billing_address.country = countries.first
    end
    form_info
  end

  # POST /shopping/addresses
  # POST /shopping/addresses.xml
  def create
    if params[:address].present?
      @billing_address = checkout_user.addresses.new(allowed_params)
      @billing_address.default = true          if checkout_user.default_billing_address.nil?
      @billing_address.billing_default = true  if checkout_user.default_billing_address.nil?
      @billing_address.save
    elsif params[:billing_address_id].present?
      @billing_address = checkout_user.addresses.find(params[:billing_address_id])
    end
    if @billing_address.id
      update_order_address_id(@billing_address.id)
      redirect_to(next_admin_order_form_url, :notice => 'Address was successfully created.')
    else
      form_info
      render :action => "new"
    end
  end

  def select_address
    address = checkout_user.addresses.find(params[:id])
    update_order_address_id(address.id)
    redirect_to next_admin_order_form_url
  end

  private

  def allowed_params
    params.require(:address).permit(:first_name, :last_name, :address1, :address2, :city, :state_id, :state_name, :zip_code, :default, :billing_default, :country_id)
  end

  def form_info
    @billing_addresses = session_admin_cart.customer.billing_addresses
    @states     = State.form_selector
  end
  def update_order_address_id(id)
    session_admin_order.update_attributes( :bill_address_id => id )
  end
end

app/controllers/admin/shopping/credit_cards_controller.rb
class Admin::Shopping::CreditCardsController < Admin::Shopping::BaseController
  # GET /admin/order/credit_cards
  def index
    @credit_cards = session_admin_cart[:user].credit_cards
  end

  # GET /admin/order/credit_cards/1
  def show
    @credit_card = session_admin_cart[:user].credit_cards.find(params[:id])
  end

  # GET /admin/order/credit_cards/new
  def new
    @credit_card = CreditCard.new(:user_id => session_admin_cart[:user].id)
  end

  # POST /admin/order/credit_cards
  def create
    @credit_card = session_admin_cart[:user].credit_cards.new(allowed_params)

    respond_to do |format|
      if @credit_card.save
        format.html { redirect_to(@credit_card, :notice => 'Credit card was successfully created.') }
      else
        format.html { render :action => "new" }
      end
    end
  end
  private

  def allowed_params
    params.require(:credit_card).permit!
  end
end

app/controllers/myaccount/orders_controller.rb
class Myaccount::OrdersController < Myaccount::BaseController
  # GET /myaccount/orders
  # GET /myaccount/orders.xml
  def index
    @orders = current_user.finished_orders.find_myaccount_details
  end

  # GET /myaccount/orders/1
  # GET /myaccount/orders/1.xml
  def show
    @order = current_user.finished_orders.includes([:invoices]).find_by_number(params[:id])
  end
  private

  def selected_myaccount_tab(tab)
    tab == 'orders'
  end
end

app/views/shopping/orders/_order_item.html.erb
<div class=' large-7 clearfix <%= cycle("line_item_blue", "line_item_light_gray") -%>'>
    <div class=' large-7 columns '>
      <%= image_tag(items.first.variant.product.featured_image(:mini)) %><br/>
      <%= items.first.variant.product.name %> <br/>
      Quantity: <%= items.size %>
    </div>
    <div class=' large-5 columns last'>
      <%= raw items.first.variant.display_property_details %>
    </div>
</div>

app/views/shopping/orders/confirmation.html.erb
<div id="order-confirmation">
  <div class="row">
    <div class='large-8 columns'>
      <div class="top-box background-gray red-border-left">
        <h3 style="margin-top:1rem;">Thank You, Your order has been placed</h3>
        <div class='row' style='margin-top:1rem;margin-left:2rem;'>
          <ul class='vertical menu large-12 columns'>
            <li>
              An email confirmation has been sent to you
            </li>
            <li>
              Order Number: <strong><%= @order.number %></strong>
            </li>
          </ul>
        </div>
      </div>
      <hr style='color:#aac;'/>
      <div>
        <% @order.order_items.group_by(&:variant_id).each do |variant_id, items| %>
          <div class='row media-object'>
            <div class='large-4 columns'>
              <%= link_to product_path(items.first.variant.product), title: items.first.variant.product.name do %>
                <%= image_tag items.first.variant.product.featured_image(:medium), class: 'thumbnail' %>
              <% end %>
            </div>
            <div class='large-8 columns'>
              <h4 class=''>
                <%= raw items.first.variant.product_name %>
              </h4>
              Qty: <%= items.size %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/shopping/orders/index.html.erb
<% content_for :head do -%>
  <%= stylesheet_link_tag 'tables.css' %>
<% end %>
<div id='order-wrapper' class='twelve'>
  <div class='seven large-7 columns'>
    <h1>Order Summary</h1>

    <div id='order-items-summary'>
      <% i = 1 %>
      <% @order.order_items.group_by(&:variant_id).each do |variant_id, items| %>
        <div id='order-item-<%= i %>' class='callout'>
          <%= render :partial => 'order_item', :locals => {:items => items } %>
        </div>
        <% i += 1 %>
      <% end %>
    </div>
    <div class='row'>
      <div id='final-order-shipping-address' class=' four large-6 columns radius' >
        <div class='callout'>
          <h5>Shipping Address</h5>
          <%= render :partial => '/shared/compact_address', :locals => {:shopping_address => @order.ship_address} %>
          <%= link_to 'Change address', shopping_addresses_path, :class => 'button tiny green' %>
        </div>
      </div>
      <div id='final-order-shipping-address' class=' four large-6 columns radius last' >
        <div class='callout'>
          <h5>Billing Address</h5>
          <%= render :partial => '/shared/compact_address', :locals => {:shopping_address => @order.bill_address} %>
          <%= link_to 'Change address', shopping_billing_addresses_path, :class => 'button tiny green' %>
        </div>
      </div>
    </div>
  </div>
  <div class='pretty_table five large-5 columns last'>
    <table>
      <thead>
        <tr class='odd'>
          <th class='column1_header'>
            Item
          </th><th>Price:</th><th>Price + Tax</th>
        </tr>
      </thead>
      <% @order.order_items.each do |item| %>
        <tr class='<%= cycle("odd", "")%> '>
          <td><%= item.variant.product.name %></td><td><%= number_to_currency item.price %></td><td><%= number_to_currency item.total %></td>
        </tr>
      <% end %>
      <tr class='odd'>
        <td></td><td>Sub-total:</td><td><%= number_to_currency @order.sub_total %></td>
      </tr>
      <tr>
        <td></td><td>Shipping Charges:</td><td><%= number_to_currency @order.shipping_charges %></td>
      </tr>
      <% if @order.coupon_amount > 0.0 %>
        <tr>
          <td></td><td>Coupon:</td><td><%= number_to_currency @order.coupon_amount %></td>
        </tr>
      <% end %>
      <% if @order.deal_amount && @order.deal_amount > 0.0 %>
        <tr>
          <td></td><td>Promotion:</td><td><%= number_to_currency @order.deal_amount %></td><td></td>
        </tr>
      <% end %>
      <tr>
        <td></td><td>Tax:</td><td><%= number_to_currency @order.taxed_amount %></td>
      </tr>
      <% if @order.amount_to_credit && @order.amount_to_credit > 0.0 %>
        <tr class='odd'>
          <td></td>
          <td>Credits:</td><td></td>
          <td><%= number_to_currency @order.amount_to_credit %></td>
        </tr>
      <% end %>

      <tfoot>
        <tr class='even'>
          <td></td><td>Total:</td><td><em><%= number_to_currency @order.credited_total %></em></td>
        </tr>
      </tfoot>
    </table>
    <div>
  </div>
    <%= form_tag( shopping_order_path(@order),
                                  method: :put,
                                  html:  {class: 'custom'},
                                  id:    'purchase_order') do  %>

      <div class="field ">
        <%= label_tag  :name %>
      </div>
<div class='clear'></div>
      <div class='row'>
        <div class="field six large-6 column">
          <%= label_tag 'First' %>
           <%= text_field_tag(:first_name, @credit_card.first_name) %>
        </div>

        <div class="field six large-6 column">
          <%= label_tag :last_name, 'Last' %>
           <%= text_field_tag(:last_name, @credit_card.last_name) %>
        </div>
      </div>
      <div class='clear'></div>
      <div class='row'>
        <div class="field twelve large-8 column">
          <%= label_tag 'Number'%>
           <%= text_field_tag(:number, @credit_card.number , class: ' disableAutoComplete', :autocomplete => "off") %>
        </div>
        <div class="field three large-3 column">
          <%= label_tag :verification_value, 'VCC'%>
           <%= text_field_tag(:verification_value, @credit_card.verification_value , class: 'disableAutoComplete', :autocomplete => "off") %>
        </div>
      </div>
      <div class='twelve large-12 clearfix custom'>
        <div class='row'>

          <div class="field column large-6">
            <%= label_tag :type, 'Type'%>
             <%= select_tag(:type,
                            options_for_select(
                              ['visa', 'mastercard'],
                              selected: @credit_card.type
                            )) %>
          </div>

          <div class="field column large-3">
            <%= label_tag :month %>
            <%= select_tag(:month,
                           options_for_select(
                             ['01', '02',  '03', '04', '05', '06', '07', '08', '09', '10', '11', '12' ],
                             selected: @credit_card.month
                           )) %>
          </div>

          <div class="field column large-3">
            <%= label_tag :year %>
             <%= select_tag(:year,
                            options_for_select(
                              (Time.zone.now.year..(Time.zone.now.year + 10)),
                              selected: @credit_card.year
                            )) %>
          </div>
        </div>
      </div>


      <%= submit_tag 'Complete Order', class: 'button success' %>
    <% end %>
  </div>
</div>